### ISSUE TITLE
add menu of browse options

### ISSUE THREAD

**Issue by jkunze** [metadata-research/yamz#13]
(see current yamz.net): high score | recent | volatile | stable | alphabetical

**Comment by machawk1** [comment]
Visit yamz.net, click "Browse", then the UI in question appears.
![browse](https://user-images.githubusercontent.com/2514780/152015731-935bcc78-f261-4bb8-9a7d-15f51cf7565e.png)

**Comment by machawk1** [comment]
As a counterpoint to @jkunze's original message, there is a UI/UX (anti-)pattern relating the number of options affecting whether an explicit list is better/worse than a dropdown. @jkunze Do you anticipate many more browsing options? If not, hiding these other options, while it would clear up the display, also means "one additional click" for sorting.

**Comment by jkunze** [comment]
I don't know. The change I'm suggesting would essentially restore on yamz.link missing functionality that's present on yamz.net. I'm certain that original functionality could benefit from further UX review for.

**Comment by machawk1** [comment]
Ok, I misunderstood. 
<img width="926" alt="Screen Shot 2022-02-02 at 1 07 37 PM" src="https://user-images.githubusercontent.com/2514780/152212213-a0620d21-e501-4a5a-b57d-cff5a234a232.png">

Here is yamz.link missing the above pictures horizontal list of links. We might also consider adding a "Sort By" label to make it clear that it is a different view on the same data rather than incurring some processing, as implied by them being naked, floating hyperlinks. Some indicator, even if not a label, would be helpful and more accessible.

**Comment by cr625** [comment]
High Score is just a sort by Score descending- the same thing as if you were to click on the column header. Do we want to make it a top 10 or something so there aren't two different labels for the same thing? Stable will return for every term right now because no one is editing terms. Recent is again sort by date descending- do we make it within some target period? 
Alphabetical- we might consider using clear filter or something like that since the default view is a paged sort alphabetical.
